Fix Error: Cannot resolve module 'string-hash'
string-hash dependency is used in DataList.js but not included in
package.json so an error occurred on startup...
Error: Cannot resolve module 'string-hash'